



spring:
  # 配置数据源
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/t84?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF8&useSSL=false&serverTimezone=Asia/Shanghai


    # MySQL在高版本需要指明是否进行SSL连接 解决则加上 &useSSL=false
    username: root
  #    password: 8317992


  redis:
    database: 11
    host: 127.0.0.1
    port: 6379
    password: 123456







mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml


server:
  port: 8896
